import { getServerSession } from "next-auth";
import { NextRequest, NextResponse } from "next/server";
import { authOptions } from "@/lib/auth";
import { db } from "@docflow/database";
import { decrypt } from "@docflow/shared";
import { Octokit } from "@octokit/rest";

export async function POST(req: NextRequest) {
  const session = await getServerSession(authOptions);
  const userId = (session?.user as any)?.id;

  if (!userId) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  try {
    const {
      repoFullName,
      content,
      branch,
      commitMessage = "docs: update README via DocFlow AI",
      createPR = false,
      prTitle,
      prBranch,
    } = await req.json();

    if (!repoFullName || !content) {
      return NextResponse.json(
        { error: "Missing required fields: repoFullName, content" },
        { status: 400 }
      );
    }

    // Verify ownership
    const repo = await db.repository.findFirst({
      where: { fullName: repoFullName, userId },
    });
    if (!repo) {
      return NextResponse.json(
        { error: "Repository not found or access denied" },
        { status: 403 }
      );
    }

    // Decrypt GitHub token
    const user = await db.user.findUnique({ where: { id: userId } });
    if (!user?.accessToken) {
      return NextResponse.json({ error: "GitHub token not available" }, { status: 401 });
    }
    const token = decrypt(user.accessToken);
    const octokit = new Octokit({ auth: token });
    const [owner, repoName] = repoFullName.split("/");
    const targetBranch = branch || repo.defaultBranch || "main";

    // Get current README SHA (if it exists)
    let currentSha: string | undefined;
    try {
      const { data } = await octokit.repos.getContent({
        owner,
        repo: repoName,
        path: "README.md",
        ref: targetBranch,
      });
      if ("sha" in data) currentSha = data.sha;
    } catch {
      // File doesn't exist yet — that's fine, we'll create it
    }

    const contentBase64 = Buffer.from(content, "utf-8").toString("base64");

    if (createPR && prBranch) {
      // Create PR flow
      const baseBranch = targetBranch;

      // Get base SHA
      const { data: refData } = await octokit.git.getRef({
        owner,
        repo: repoName,
        ref: `heads/${baseBranch}`,
      });
      const baseSha = refData.object.sha;

      // Create new branch
      try {
        await octokit.git.createRef({
          owner,
          repo: repoName,
          ref: `refs/heads/${prBranch}`,
          sha: baseSha,
        });
      } catch (e: any) {
        if (!e.message?.includes("already exists")) throw e;
      }

      // Commit to the new branch
      let sha: string | undefined;
      try {
        const { data: existing } = await octokit.repos.getContent({
          owner,
          repo: repoName,
          path: "README.md",
          ref: prBranch,
        });
        if ("sha" in existing) sha = existing.sha;
      } catch {}

      await octokit.repos.createOrUpdateFileContents({
        owner,
        repo: repoName,
        path: "README.md",
        message: commitMessage,
        content: contentBase64,
        branch: prBranch,
        sha,
      });

      // Open PR
      const { data: pr } = await octokit.pulls.create({
        owner,
        repo: repoName,
        title: prTitle || "docs: Update README via DocFlow AI",
        head: prBranch,
        base: baseBranch,
        body: "This pull request was generated by [DocFlow AI](https://docflow.ai).",
      });

      // Save draft
      await db.readmeDraft.upsert({
        where: { repositoryId: repo.id },
        update: { content },
        create: { repositoryId: repo.id, content },
      });

      return NextResponse.json({ success: true, prUrl: pr.html_url, prNumber: pr.number });
    }

    // Direct commit
    await octokit.repos.createOrUpdateFileContents({
      owner,
      repo: repoName,
      path: "README.md",
      message: commitMessage,
      content: contentBase64,
      branch: targetBranch,
      sha: currentSha,
    });

    // Update generated readme in cache
    await db.cachedFacts.updateMany({
      where: { repositoryId: repo.id },
      data: { generatedReadme: content },
    });

    // Save draft
    await db.readmeDraft.upsert({
      where: { repositoryId: repo.id },
      update: { content },
      create: { repositoryId: repo.id, content },
    });

    return NextResponse.json({ success: true });
  } catch (err: any) {
    console.error("[readme/push] Error:", err);
    const status =
      err.status === 403 ? 403 : err.status === 404 ? 404 : 500;
    return NextResponse.json(
      { error: err.message ?? "Failed to commit README" },
      { status }
    );
  }
}
