import simpleGit, { type SimpleGit } from "simple-git";
import { Octokit } from "@octokit/rest";
import { createAppAuth } from "@octokit/auth-app";
import * as path from "node:path";
import * as fs from "node:fs";
import * as os from "node:os";

// ─── Git Operations ───────────────────────────────────────────────────────────

/**
 * Shallow-clones a repository for analysis.
 * Returns the local path and a cleanup function.
 */
export async function cloneRepo(
  repoFullName: string,
  installationId: number,
  branch: string
): Promise<{ localPath: string; cleanup: () => Promise<void> }> {
  const token = await getInstallationToken(installationId);
  const cloneUrl = `https://x-access-token:${token}@github.com/${repoFullName}.git`;

  const tmpDir = path.join(
    os.tmpdir(),
    `docflow-${Date.now()}-${Math.random().toString(36).slice(2)}`
  );
  fs.mkdirSync(tmpDir, { recursive: true });

  const git: SimpleGit = simpleGit();

  await git.clone(cloneUrl, tmpDir, [
    "--depth=1",
    "--single-branch",
    `--branch=${branch}`,
    "--no-tags",
  ]);

  return {
    localPath: tmpDir,
    cleanup: async () => {
      await fs.promises.rm(tmpDir, { recursive: true, force: true });
    },
  };
}

/**
 * Commits changed README files to a new bot branch and opens a PR.
 */
export async function commitAndOpenPR(options: {
  repoFullName: string;
  installationId: number;
  baseBranch: string;
  commitSha: string;
  patchedFiles: Array<{ path: string; content: string }>;
}): Promise<{ prUrl: string; prNumber: number }> {
  const { repoFullName, installationId, baseBranch, commitSha, patchedFiles } = options;
  const [owner, repo] = repoFullName.split("/");

  const token = await getInstallationToken(installationId);
  const octokit = new Octokit({ auth: token });

  // Create bot branch name
  const botBranch = `docflow/update-docs-${commitSha.slice(0, 7)}`;

  // Get the base branch SHA
  const { data: baseBranchData } = await octokit.rest.git.getRef({
    owner,
    repo,
    ref: `heads/${baseBranch}`,
  });
  const baseSha = baseBranchData.object.sha;

  // Create the bot branch
  await octokit.rest.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${botBranch}`,
    sha: baseSha,
  });

  // Commit each patched file
  for (const file of patchedFiles) {
    // Get current file SHA (needed to update)
    let currentSha: string | undefined;
    try {
      const { data } = await octokit.rest.repos.getContent({
        owner,
        repo,
        path: file.path,
        ref: botBranch,
      });
      if (!Array.isArray(data) && data.type === "file") {
        currentSha = data.sha;
      }
    } catch {
      // File doesn't exist yet — that's fine
    }

    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: file.path,
      message: `docs: auto-update ${file.path} via DocFlow AI [skip ci]`,
      content: Buffer.from(file.content).toString("base64"),
      branch: botBranch,
      sha: currentSha,
    });
  }

  // Open the PR
  const { data: pr } = await octokit.rest.pulls.create({
    owner,
    repo,
    title: `📚 DocFlow AI: Auto-updated documentation`,
    body: generatePrBody(patchedFiles, commitSha),
    head: botBranch,
    base: baseBranch,
  });

  return { prUrl: pr.html_url, prNumber: pr.number };
}

// ─── GitHub App Authentication ────────────────────────────────────────────────

const tokenCache = new Map<number, { token: string; expiresAt: Date }>();

async function getInstallationToken(installationId: number): Promise<string> {
  // Check cache (tokens last 1 hour, we refresh 5 min early)
  const cached = tokenCache.get(installationId);
  if (cached && cached.expiresAt > new Date(Date.now() + 5 * 60 * 1000)) {
    return cached.token;
  }

  const appId = process.env.GITHUB_APP_ID;
  const privateKey = process.env.GITHUB_PRIVATE_KEY?.replace(/\\n/g, "\n");

  if (!appId || !privateKey) {
    throw new Error(
      "[DocFlow GitHub] GITHUB_APP_ID and GITHUB_PRIVATE_KEY must be set"
    );
  }

  const auth = createAppAuth({
    appId: parseInt(appId),
    privateKey,
  });

  const installationAuth = await auth({
    type: "installation",
    installationId,
  });

  const expiresAt = new Date(installationAuth.expiresAt);
  tokenCache.set(installationId, { token: installationAuth.token, expiresAt });

  return installationAuth.token;
}

// ─── PR Body ──────────────────────────────────────────────────────────────────

function generatePrBody(
  patchedFiles: Array<{ path: string; content: string }>,
  commitSha: string
): string {
  return `## 📚 DocFlow AI — Automated Documentation Update

This PR was automatically generated by [DocFlow AI](https://github.com/your-org/docflow-ai) in response to commit \`${commitSha.slice(0, 7)}\`.

### Updated Files
${patchedFiles.map((f) => `- \`${f.path}\``).join("\n")}

### How it works
- ✅ **Parser-First**: Raw source code never entered the AI context
- ✅ **Surgical edit**: Only sections with changed facts were updated
- ✅ **Prompt-injection safe**: Structured JSON facts only
- ✅ **Validated**: Markdown was linted before this PR was opened

---
*Review the changes and merge if they look accurate. To disable auto-docs for this repo, visit your [DocFlow AI Dashboard](http://localhost:3000/dashboard).*`;
}
